name: build

on: [push, pull_request]

env:
  SLN:  CsvLINQPadDriver.sln
  SLN5: CsvLINQPadDriver.LINQPad5.sln
  SLN_CONFIG: Release
  BIN_POSTFIX: .Bin
  RETENTION_DAYS: 1

jobs:
  build:
    runs-on: windows-latest

    steps:

    # Setup

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          8.0.x

    # Checkout

    - name: Checkout
      uses: actions/checkout@v4.1.1

    # LINQPad 7/6

    - name: ${{env.SLN}} restore dependencies
      run: dotnet restore ${{env.SLN}}

    - name: ${{env.SLN}} ${{env.SLN_CONFIG}} build
      run: dotnet build ${{env.SLN}} --configuration ${{env.SLN_CONFIG}} --no-restore -p:GITHUB_ACTIONS=true

    - name: ${{env.SLN}} ${{env.SLN_CONFIG}} test
      run: dotnet test ${{env.SLN}} --configuration ${{env.SLN_CONFIG}} --no-build --verbosity normal

    # LINQPad 5

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.3.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.3.0

    - name: ${{env.SLN5}} restore dependencies
      run: nuget restore ${{env.SLN5}}

    - name: ${{env.SLN5}} ${{env.SLN_CONFIG}} build
      run: msbuild ${{env.SLN5}} /p:Configuration=${{env.SLN_CONFIG}}

    # Create LPX

    - name: Build LPX
      run: Deploy/buildlpx.cmd

    # Upload artifacts

    - name: Publish CsvLINQPadDriver
      uses: actions/upload-artifact@v4.3.0
      with:
        name: CsvLINQPadDriver${{env.BIN_POSTFIX}}
        path: |
          bin/${{env.SLN_CONFIG}}/CsvLINQPadDriver.*.*nupkg
          Deploy/*.lpx
          Deploy/*.lpx?
        retention-days: ${{env.RETENTION_DAYS}}

    - name: Publish LPRun
      uses: actions/upload-artifact@v4.3.0
      with:
        name: LPRun${{env.BIN_POSTFIX}}
        path: bin/${{env.SLN_CONFIG}}/LPRun.*.*nupkg
        retention-days: ${{env.RETENTION_DAYS}}
