name: build

on: [push, pull_request, workflow_dispatch]

env:
  NAME: CsvLINQPadDriver
  SLN:  CsvLINQPadDriver.sln
  SLN5: CsvLINQPadDriver.LINQPad5.sln
  CONFIG: Release
  BIN_POSTFIX: .Bin
  RETENTION_DAYS: 1

jobs:
  build:
    runs-on: windows-latest

    steps:

    # Set up

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: |
          9.0.x

    # Check out

    - name: Check out ${{env.SLN}}
      uses: actions/checkout@v4.2.2

    # LINQPad 8/7/6

    - name: Build ${{env.SLN}} ${{env.CONFIG}}
      run: dotnet build ${{env.SLN}} --configuration ${{env.CONFIG}} -p:GITHUB_ACTIONS=true

    - name: Test ${{env.SLN}} ${{env.CONFIG}}
      run: dotnet test ${{env.SLN}} --configuration ${{env.CONFIG}} --no-build --verbosity normal

    - name: Create ${{env.SLN}} ${{env.CONFIG}} test report
      uses: dorny/test-reporter@v1.9.1
      if: ${{success() || failure()}}
      with:
        name: tests
        path: '**/*.trx'
        reporter: dotnet-trx

    # LINQPad 5

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.1

    - name: Restore ${{env.SLN5}}
      run: nuget restore ${{env.SLN5}}

    - name: Build ${{env.SLN5}} ${{env.CONFIG}}
      run: msbuild ${{env.SLN5}} /p:Configuration=${{env.CONFIG}}

    # Create LPX

    - name: Build LPX
      run: Deploy/buildlpx.cmd

    # Upload artifacts

    - name: Publish ${{env.SLN}} ${{env.CONFIG}}, ${{env.SLN5}} ${{env.CONFIG}}
      uses: actions/upload-artifact@v4.6.0
      with:
        name: ${{env.NAME}}${{env.BIN_POSTFIX}}
        path: |
          bin/${{env.CONFIG}}/${{env.NAME}}.*.*nupkg
          Deploy/*.lpx
          Deploy/*.lpx?
        retention-days: ${{env.RETENTION_DAYS}}
